<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="gowano" failures="1" tests="1" name="PlaceOrderWithReport" time="51.083" errors="0" timestamp="2025-04-12T04:53:25 EET" skipped="0">
  <testcase classname="PlaceOrderWithReport" name="testPlaceOrder" time="51.083">
    <failure message="The following asserts failed:
	Test 3: Bug: Invalid data was accepted. Issues: Empty country; ,
	Test 4: Bug: Invalid data was accepted. Issues: Empty city; ,
	Test 6: Bug: Invalid data was accepted. Issues: Empty month; Empty year; " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Test 3: Bug: Invalid data was accepted. Issues: Empty country; ,
Test 4: Bug: Invalid data was accepted. Issues: Empty city; ,
Test 6: Bug: Invalid data was accepted. Issues: Empty month; Empty year; 
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at PlaceOrderWithReport.testPlaceOrder(PlaceOrderWithReport.java:199)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at MainTest.main(MainTest.java:123)
]]>
    </failure>
  </testcase> <!-- testPlaceOrder -->
  <system-out/>
</testsuite> <!-- PlaceOrderWithReport -->
